services:
  app:
    build: .
    image: web-service-employees-app
    ports:
      - 8090:8090
    environment:
      APP_MONGO_CONSTR: mongodb://storage:27017/employeeStorage?timeoutMS=10000&maxPoolSize=99
      APP_SERVER_SOCKET: 0.0.0.0:8090

  storage:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: employeeStorage
    volumes:
      - ./script/schema.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://storage:27017

networks:
  default:
    name: web-service-employees
